### ISSUE TITLE
trailing postgres cluster

### ISSUE THREAD

**Issue by kardaj** [tk0miya/testing.postgresql#9] opened 2016-01-25 10:37 UTC
Hi, I'm using the following snippet to run my tests.
```python
import unittest
import testing.postgresql


class MyTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(self):
        self.postgresql = testing.postgresql.Postgresql()

    @classmethod
    def tearDownClass(self):
        self.postgresql.stop()
```

The problem I'm currently having is that the testing postgres cluster doesn't shutdown if my test run into an Error. Is there a way to avoid this?

**Comment by tk0miya** [comment] 2016-02-06 02:17
I tried the your script as a test, then postgresql shutdown safely.
I used `unittest.main()`, `nosetests` and `py.test` as test runners.
I added following testcase. It raises a simple exception.
```
    def test_failed(self):
        raise
```

Could you tell me your situation in detail?

**Comment by kardaj** [comment] 2016-02-09 10:22
After further analysis, I think it's more of a unittest problem. Here's some code that will generate a trailing test cluster:

```python
import unittest
import testing.postgresql


class MyTestCase(unittest.TestCase):

    @classmethod
    def setUpClass(self):
        print 'setUpClass'
        self.postgresql = testing.postgresql.Postgresql()
        import inexistingpackage

    @classmethod
    def tearDownClass(self):
        print 'tearDownClass'
        self.postgresql.stop()

    def test_error(self):
        cur.help()

    def test_working(self):
        'working test'
        assert 1

```

In this code, an error occurred during the setup phase. This leads to unittest stopping and `tearDownClass` not being called at all.

**Comment by tk0miya** [comment] 2016-02-11 12:51
I understand.
Test runners skips `tearDownClass` if `setUpClass` got error. It's rule of `unittest.TestCase`.

Please rewrite your `setUpClass` like following:
```
    @classmethod
    def setUpClass(self):
        print 'setUpClass'
        try:
             self.postgresql = testing.postgresql.Postgresql()
             import inexistingpackage
        except:
             self.postgresql.stop()
```

I think this is not a bug of `testing.postgresql`. so I close this.

Thanks,

**Closed by tk0miya** 2016-02-11 12:51 UTC
